spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/chibiotaku_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
    password: 1234
    username: root



  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  # with this setup you can have put delete and so on methods
  mvc:
    hiddenmethod:
      filter:
        enabled: true
